### ISSUE TITLE
Bring back node 4.x support by using scrict mode

### ISSUE THREAD

**Issue by Apollon77** [hobbyquaker/cul#12]
Hi,

with 0.5.0 you removed nodejs 4.x support. For ioBroker I had the idea to update to 0.5 of the lib for the ioBroker.cul adapter, but loosing nodejs 4 is hard.

You can bring back nodejs 4 support by simply using sctrict mode (add "'use strict';" to all fixes on top). Then you get back nodejs 4: https://travis-ci.org/Apollon77/cul/builds/332285922

But I needed to remove the "xo" checks because it seems that they get "harder" when files are in strict mode (e.g. https://travis-ci.org/Apollon77/cul/jobs/332284580) ... wanted to clarify it first before bringing in an PR :-)

What do you think?

**Comment by hobbyquaker** [comment]
added the strict mode, but i think node 4 should not be relevant anymore. It's already out of active lts and maintanence lts ends in april, so people should update sooner or later anyways ;)

**Comment by Apollon77** [comment]
Thank you!
I completely agree. ioBroker currently has nodejs 4 as minimum and I assume longer then officially supported ... :-(

**Comment by Apollon77** [comment]
virtual-serialport is not compatible with serialport 6.x as soon as you start with Parsers :-( so maybe needs longer to get some testing
