### ISSUE TITLE
node-red wrapper

### ISSUE THREAD

**Issue by ctr49** [hobbyquaker/cul#6]
Great work!
I'm currently using FHEM as gateway from EIB/KNX to InterTechno (via CUL433) and from EnOcean (via EUL), however I plan to switch to Node-Red as logic engine (and as result also as gateway replacement). Do you plan to also provide a node-red wrapper for cul.js?

**Comment by hobbyquaker** [comment]
No, I have no plans to create a node-red cul node. But I can suggest another solution: https://github.com/hobbyquaker/cul2mqtt - that can be easily used in conjunction with Node-RED via MQTT.

**Comment by hobbyquaker** [comment]
btw - there is also https://github.com/owagner/eno2mqtt and https://github.com/owagner/knx2mqtt

**Comment by ctr49** [comment]
Afaict cul2mqtt is only unidirectional, while I'm looking for something2cul instead. I managed to get it working by directly attaching node-red to the serial port and sending commanda like "isXXXXXXXX".
